service: ssr-demo
plugins:
  - serverless-apigw-binary
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 10
  stage: "production"
package:
  exclude:
    - ./**
  include:
    - "node_modules/aws-serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "dist/**"
    - "lambda.js"
custom:
  apigwBinary:
    types:
      - "*/*"
  contentEncoding:
    contentCompression: 1000
functions:
  api:
    handler: lambda.handler
    events:
      - http: GET {proxy+}
      - http: GET /